default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["DEV_DATABASE_NAME"] %>
  username: <%= ENV["DEV_DATABASE_USERNAME"] %>
  password: <%= ENV["DEV_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: <%= ENV["TEST_DATABASE_NAME"] %>
  username: <%= ENV["TEST_DATABASE_USERNAME"] %>
  password: <%= ENV["TEST_DATABASE_PASSWORD"] %>
 
production:
  <<: *default
  #url: <%= ENV['PROD_DATABASE_URL'] %> possible use for this variable
  database: <%= ENV["PROD_DATABASE_NAME"] %>
  username: <%= ENV["PROD_DATABASE_USERNAME"] %>
  password: <%= ENV["PROD_DATABASE_PASSWORD"] %>